### PR TITLE
Migrate tests to jest

### PR DESCRIPTION
**Pull request by stellarhoof**
Most changes come from `package-lock.json`

This migration is straight-forward. All chai matchers/sinon spies have an equivalent in jest.

### CODE REVIEW

**Comment by decrapifier** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Danger failed to run `/home/runner/work/contexture-client/contexture-client/node_modules/duti/src/dangerfile.js`.
  </td>
    </tr>
  </tbody>
</table>



## Error Error
```

Error
    at /home/runner/work/contexture-client/contexture-client/node_modules/duti/src/utils.js:37:11
    at async /home/runner/work/contexture-client/contexture-client/node_modules/duti/src/dangerfile.js:36:20
    at async Promise.all (index 0)
```
### Dangerfile
```
32|       markdown: log(markdown),
33|       config,
34|       message: log(message),
35|       lintResults: await getLintResults({ config }),
36|       testResults: await getTestResults({ config }),
-------------^
37|       browserResults: await getBrowserResults({ config }),
38|     })
39|   )
40| })
```
  
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 95c9872cfede6370177a38ec9360de77c8ad1c03
</p>

**Comment by stellarhoof** [comment]
@daedalus28 I've never seen us care for coverage so I removed it. If you think it's important I can add it back.

**Review by rudolph9 — APPROVED** [review]
Only feedback I have to make sure we we're careful about `toBe` vs `toEqual`. This is probably something you and @daedalus28 should talk through.

* https://jestjs.io/docs/expect#tobevalue
* https://jestjs.io/docs/expect#toequalvalue
* good SO post comparing the two https://stackoverflow.com/questions/45195025/what-is-the-difference-between-tobe-and-toequal-in-jest

**Comment by stellarhoof** [comment]
I made sure to use `toBe` for primitives and `toEqual` for every other case.

**Comment by daedalus28** [comment]
> @daedalus28 I've never seen us care for coverage so I removed it. If you think it's important I can add it back.

Coverage is probably something we should be more intentional about, especially for critical core things like this. Let's add it back 👍  I think jest has something native for it.

Also, there are some conflicts from your other PR

**Review by ccalbaugh — APPROVED** [review]

**Comment by stellarhoof** [comment]
@daedalus28 This is gtg

**Review by rudolph9 — APPROVED** [review]

**Pull request merged**
